#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # 设置 SpaceVim 主题及背景，默认的主题是 gruvbox，如果你需要使用更
    # 多的主题，你可以载入 colorscheme 模块
    # colorscheme = "gruvbox"

    colorscheme = "OceanicNext"
    colorscheme_bg = "dark"

    # colorscheme = "NeoSolarized"
    # colorscheme_bg = "light"
    # 背景可以取值 "dark" 和 "light"

    # 启用/禁用终端真色，在目前大多数终端下都是支持真色的，当然也有
    # 一小部分终端不支持真色，如果你的 SpaceVim 颜色看上去比较怪异
    # 可以禁用终端真色，将下面的值设为 false
    enable_guicolors = true
    # 设置状态栏上分割符号形状，如果字体安装失败，可以将值设为 "nil" 以
    # 禁用分割符号，默认为箭头 "arrow"
    statusline_separator = "nil"
    statusline_separator = "bar"
    # 设置顶部标签列表序号类型，有以下五种类型，分别是 0 - 4
    # 0: 1 ➛ ➊ 
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 
    buffer_index_type = 4
    # 显示/隐藏顶部标签栏上文件类型图标，这一图标需要安装 nerd fonts，
    # 如果未能成功安装这一字体，可以隐藏图标
    enable_tabline_filetype_icon = true
    # 是否在状态栏上显示当前模式，默认情况下，不显示 Normal/Insert 等
    # 字样，只以颜色区分当前模式
    enable_statusline_display_mode = false

    # MY OWN OPTIONS
    filemanager = "defx"
    autocomplete_method = "coc"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# ----------------- SpaceVim 添加的各种 layers ---------------------------------

# 计算器 日历 书签等小工具
[[layers]]
  name = 'tools'

# 禁用 SpaceVim 的 checkers layer
[[layers]]
  name = "checkers"
  enable = false

# 版本控制
[[layers]]
  name = "VersionControl"
  enable-gtm-status = true

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
  name = "lang#markdown"

# ----------------- 添加的插件 -------------------------------------------------

# oceanic-next 主题，采用其他的主题可以删除
[[custom_plugins]]
  name = "mhartington/oceanic-next"
  merged = 0

# coc.nvim 核心配置，不要删除
[[custom_plugins]]
  name = 'neoclide/coc.nvim'
  merge = 0
  build =  'yarn install --frozen-lockfile'

# 主要用于快速搜索 文件, buffer 和 函数
[[custom_plugins]]
    name = "Yggdroot/LeaderF"
    build = "./install.sh"

# 快速编辑 markdown 表格
[[custom_plugins]]
  name = 'dhruvasagar/vim-table-mode'

# vista.vim 的依赖
[[custom_plugins]]
    name = 'junegunn/fzf'
    merged =  0

# vista.vim 的依赖
[[custom_plugins]]
    name = "majutsushi/tagbar"

# 更加美观的 tagbar 
[[custom_plugins]]
    name = 'liuchengxu/vista.vim'

# 更加方便的调节窗口的大小
[[custom_plugins]]
    name = 'simeji/winresizer'

# 比 nerdcommentary 更好用的注释工具
[[custom_plugins]]
    name = 'tpope/vim-commentary'

# 时间统计工具，配合商业网站 https://wakatime.com/ 使用
[[custom_plugins]]
    name = 'wakatime/vim-wakatime'

# 基于lsp的高亮插件
[[custom_plugins]]
    name = 'jackguo380/vim-lsp-cxx-highlight'

# https://github.com/skywind3000/asyncrun.vim
# 本插件使用 Vim 8 / NeoVim 的异步机制，让你在后台运行 shell 命令，
# 并将结果实时显示到 Vim 的 Quickfix 窗口中：
[[custom_plugins]]
    name = 'skywind3000/asyncrun.vim'

# 从 http://cplusplus.com/ 和 http://cppreference.com/ 获取文档
[[custom_plugins]]
    name = 'skywind3000/vim-cppman'

# vim小游戏，使用 :VimGameCodeBreak 运行
[[custom_plugins]]
    name = 'johngrib/vim-game-code-break'


# ----------------- 垃圾堆，不用理会 -------------------------------------------
#
# https://github.com/high-moctane/asyncomplete-nextword.vim # 也许是解救我的写作的位置了
# https://github.com/jceb/vim-orgmode/blob/master/doc/orgguide.txt
# https://github.com/vivien/vim-linux-coding-style 内核 C 语言风格

# 实现括号颜色配对 和 vim-lsp-cxx-highlight 冲突，需要手动设置
# [[custom_plugins]]coc.nvim
#     name =  'luochen1990/rainbow'

# 编辑 hex 文件
# [[custom_plugins]]
#     name = 'Shougo/vinarise.vim'

# 键盘声音
# [[custom_plugins]]
    # name = 'skywind3000/vim-keysound'
# 配套使用的UI系统
# [[custom_plugins]]
#     name = 'waldson/vui'

# [[custom_plugins]]
#     name = 'AndrewRadev/splitjoin.vim'

# 当进入到 window 的时候自动调节其大小，有点bug
# [[custom_plugins]]
#     name = 'camspiers/animate.vim'
# [[custom_plugins]]
#     name = 'camspiers/lens.vim'

# 用于预览 reStructuredText 文件，但是无法正常工作
# [[custom_plugins]]
#     name = 'Rykka/riv.vim'
# [[custom_plugins]]
#     name = 'Rykka/InstantRst'

# 一个有意思的同步软件
# [[custom_plugins]]
    # name = 'kenn7/vim-arsync'
    # merged =  0

# two cppman tools, waiting for it complete 
# [[custom_plugins]]
#     name = 'gauteh/vim-cppman'
# [[custom_plugins]]
#     name = 'skywind3000/vim-cppman'

# Failed to install
# https://www.reddit.com/r/neovim/comments/ezs67g/neovim_plugin_that_provides_fzf_preset_with/
# [[custom_plugins]]
#     name = 'yuki-ycino/fzf-preview.vim'

# vim game based on new features of Vim 8.2，it doesn't work on nvim 4.3
# [[custom_plugins]]
#     name = 'vim/killersheep'

# [[custom_plugins]]
#     name = 'vhda/verilog_systemverilog.vim'

# interesting plug
# https://github.com/janko/vim-test
# https://github.com/justinmk/vim-sneak seems better than easymotion
# https://github.com/prettier/vim-prettier a format for many languages we don't have 
#
# relearn vim about how to move and edit more quickly !
# https://github.com/tpope/vim-repeat
# https://github.com/tpope/vim-surround


# After instaling this plugin, it seems nothing changed !
# [[custom_plugins]]
    # name = 'sheerun/vim-polyglot'

# [[custom_plugins]]
  # name = 'sedm0784/vim-you-autocorrect'

# maybe useful
# tpope/vim-surround
# terryma/vim-multiple-cursors

# another debug framework
# https://github.com/puremourning/vimspector#faq
#
# debug for vim doesn't work well so far !
# https://github.com/idanarye/vim-vebugger
# [[layers]]
  # name = "debug"

# https://github.com/kristijanhusak/defx-icons
# maybe file icon is not so easy to support for defx-icons
# [[custom_plugins]]
#     name = 'kristijanhusak/defx-icons'

# [[custom_plugins]]
#     name =  "Shougo/vimproc.vim"
#     build = "make"

# [[custom_plugins]]
#     name = 'Shougo/neoinclude.vim'

# [[custom_plugins]]
#     name = 'jsfaint/coc-neoinclude'
#
# 几个语言的支持，其他的语言支持利用 coc.nvim 
# 能不能直接利用 SpaceVim 中间 lsp 的支持
# [[layers]]
#   name = "lang#vim"

# [[layers]]
#   name = "lang#latex"

# 看一下吧
# https://github.com/sakhnik/nvim-gdb
