#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # 设置 SpaceVim 主题及背景，默认的主题是 gruvbox，如果你需要使用更
    # 多的主题，你可以载入 colorscheme 模块
    colorscheme = "gruvbox"

    # 启用/禁用终端真色，在目前大多数终端下都是支持真色的，当然也有
    # 一小部分终端不支持真色，如果你的 SpaceVim 颜色看上去比较怪异
    # 可以禁用终端真色，将下面的值设为 false
    enable_guicolors = true
    # 设置状态栏上分割符号形状，如果字体安装失败，可以将值设为 "nil" 以
    # 禁用分割符号，默认为箭头 "arrow"
    statusline_separator = "nil"
    statusline_separator = "bar"
    # 设置顶部标签列表序号类型，有以下五种类型，分别是 0 - 4
    # 0: 1 ➛ ➊ 
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 
    buffer_index_type = 4
    # 显示/隐藏顶部标签栏上文件类型图标，这一图标需要安装 nerd fonts，
    # 如果未能成功安装这一字体，可以隐藏图标
    enable_tabline_filetype_icon = true
    # 是否在状态栏上显示当前模式，默认情况下，不显示 Normal/Insert 等
    # 字样，只以颜色区分当前模式
    enable_statusline_display_mode = false

    # 自定义配置
    filemanager = "defx"
    autocomplete_method = "coc"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    # indent-blankline.nvim 会在一些奇怪的位置（比如 filetree 中）放置竖线
    disabled_plugins = ["indent-blankline.nvim"]

# ----------------- SpaceVim 添加的各种 layers ---------------------------------
[[layers]]
  name = 'core'
  # 不让 filetree 显示 git 的状态，在大项目中性能有点问题
  enable_filetree_gitstatus = false
  # 让file tree 显示文件图标，需要 terminal 安装 nerd font
  enable_filetree_filetypeicon = true

# 计算器, 日历, 书签等小工具
[[layers]]
  name = 'tools'

# 禁用 SpaceVim 的 checkers layer, 让 coc.nvim 来管理
[[layers]]
  name = "checkers"
  enable = false

# 版本控制
[[layers]]
  name = "VersionControl"
  enable-gtm-status = true

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
  name = "fzf"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#latex"

# ----------------- 添加的插件 -------------------------------------------------
# coc.nvim 核心配置，不要删除
[[custom_plugins]]
  name = 'neoclide/coc.nvim'
  merge = 0

# 优化 coc 的搜索界面
[[custom_plugins]]
  name = 'antoinemadec/coc-fzf'
  branch = 'release'

[[custom_plugins]]
    name = 'junegunn/fzf.vim'

# 快速编辑 markdown 的表格
[[custom_plugins]]
  name = 'dhruvasagar/vim-table-mode'

# 更加美观的 tagbar 
[[custom_plugins]]
    name = 'liuchengxu/vista.vim'

# 更加方便的调节窗口的大小
[[custom_plugins]]
    name = 'simeji/winresizer'

# 为 c/cpp 提供基于 lsp 的高亮
[[custom_plugins]]
    name = 'jackguo380/vim-lsp-cxx-highlight'

# 从 http://cplusplus.com/ 和 http://cppreference.com/ 获取文档
[[custom_plugins]]
    name = 'skywind3000/vim-cppman'

# 利用 git blame 显示当前行的 commit message
[[custom_plugins]]
    name = 'rhysd/git-messenger.vim'
    lazy =  1
    on_cmd = 'GitMessenger'

# 以悬浮窗口的形式打开终端
[[custom_plugins]]
    name = 'voldikss/vim-floaterm'

# 显示搜索的标号
[[custom_plugins]]
    name = 'google/vim-searchindex.git'

# 安装公共的的 snippets
[[custom_plugins]]
    name = 'honza/vim-snippets'

# 一些 lua 插件，比如 telescope, 的依赖
[[custom_plugins]]
    name = 'nvim-lua/plenary.nvim'

# 安装 telescope 来实现搜索
[[custom_plugins]]
    name = 'nvim-telescope/telescope.nvim'

# 使用 telescope 来搜索 coc 提供的符号
[[custom_plugins]]
    name = 'fannheyward/telescope-coc.nvim'

# 配合 sourcetrail 使用
[[custom_plugins]]
  name = 'CoatiSoftware/vim-sourcetrail'

[[custom_plugins]]
  name = 'nvim-treesitter/nvim-treesitter'
  # build = ':TSUpdate'

[[custom_plugins]]
  name = 'nvim-telescope/telescope-fzf-native.nvim'
  build = 'make'

# ----------------- 尝试的内容 -------------------------------------------------
# 暂无
