session_name: note
windows:
  - window_name: vn
    layout: tiled
    shell_command_before:
      - cd ~/core/vn
      - mkdir -p /tmp/martins3/nvim/ && nvim --listen /tmp/martins3/nvim/$(uuidgen)
  - window_name: dotfiles
    layout: tiled
    shell_command_before:
      - cd ~/.dotfiles/
      - mkdir -p /tmp/martins3/nvim/ && nvim --listen /tmp/martins3/nvim/$(uuidgen)
