session_name: code
windows:
  - window_name: linux
    layout: tiled
    shell_command_before:
      - cd ~/core/linux
      - mkdir -p /tmp/martins3/nvim/ && nvim --listen /tmp/martins3/nvim/$(uuidgen)
  - window_name: qemu
    layout: tiled
    shell_command_before:
      - cd ~/core/qemu
      - mkdir -p /tmp/martins3/nvim/ && nvim --listen /tmp/martins3/nvim/$(uuidgen)
